### ISSUE TITLE
Block breaking texture is black when using Iris

### ISSUE THREAD

**Issue by I-like-Portal-2** [leo60228/VanillAA-Shaders#1]
Hi, i really love this shader, as far as i know, it's the only shader, that adds nothing exept anti-aliasing! hovewer, i have a problem with Iris shaders mod, you can see it on the picture below.
How it looks like (with VanillAA)
![2022-11-26_13 15 25](https://user-images.githubusercontent.com/99472757/204083677-452fd5ef-d09a-4f93-9d0b-c04d3a7e433c.png)
How it suppoused to look like (without VanillAA)
![2022-11-26_13 14 48](https://user-images.githubusercontent.com/99472757/204083698-ca0b1247-bb25-45fb-a0e2-423b61ee7221.png)
I know nothing about shaders, but some of them, for example: 

_**Sildur's Basic Shaders
Sildur's Enhanced Defalut Shaders
Tea Shaders**_

have this issue too, but shaders like:

**_BSL Shaders
Complementary Shaders
Complementary Reimagined
MakeUp UltraFast
Sildur's Vibrant Shaders_**

don't have this issue. I love your work, minecraft without AA seems unplayable for me. Please, can you fix it? It would mean a lot to me. Thank you!

**Comment by I-like-Portal-2** [comment]
UPDATE: [this guy](https://github.com/IrisShaders/Iris/issues/951#issuecomment-1028645395) fixed it, it works for me!

**Comment by leo60228** [comment]
Fixed in 1.1.
