### ISSUE TITLE
Fog is different when using shader

### ISSUE THREAD

**Issue by eliu9395** [leo60228/VanillAA-Shaders#10]
In the overworld, the fog starts a bit closer than normal. When I go underwater, fog starts noticeably farther, and it also causes color banding. In the end, the sky changes color as well, and in lava, I can see everything.

I'm using Iris.

**Comment by leo60228** [comment]
I'm pretty sure the fog implementation is incorrect on 1.17+ (it relies on a compatibility feature in Iris), though I'm not sure what the *correct* behavior is. I think #9 should fix this, I'll look in to it.

**Comment by leo60228** [comment]
Will be fixed in 1.3.
