### ISSUE TITLE
Blindness fog doesn't work

### ISSUE THREAD

**Issue by leo60228** [leo60228/VanillAA-Shaders#2]
I'm not sure how to implement this, might investigate more later.

**Comment by Michael1297** [comment]
I think the problem is in this formula: https://github.com/leo60228/VanillAA-Shaders/blob/541845be6d5dc5051d9480c4f67d6d714e9da71a/shaders/gbuffers_textured.fsh#L26

my fix: `vec3 light = texture2D(lightmap,coord1).rgb;`

**Comment by leo60228** [comment]
I'm not at my computer, does that still render the fog like vanilla does or
does it just disable blindness entirely? If it still has the fog then
that's definitely the right fix.

**Comment by leo60228** [comment]
Fixed in 1.2.
