### ISSUE TITLE
loses text color in 1.8.9 / 1.12.2 mc

### ISSUE THREAD

**Issue by Michael1297** [leo60228/VanillAA-Shaders#3]
![2023-01-02_21 08 19](https://user-images.githubusercontent.com/38764610/210266415-b3462d9a-225b-4754-a017-7b1bb572ccea.png)

I am new to glsl programming. I think the problem is in this formula:
https://github.com/leo60228/VanillAA-Shaders/blob/541845be6d5dc5051d9480c4f67d6d714e9da71a/shaders/gbuffers_textured.vsh#L38

my fix: `vec3 normal = normalize(gl_NormalMatrix * gl_Normal);`

**Comment by leo60228** [comment]
(Sorry for taking so long to get to this issue! I saw it a while ago, but I thought I'd already responded...) This shaderpack primarily targets modern Iris, but that fix looks reasonable. I'll include it in the next update assuming it doesn't cause issues on modern versions.

**Comment by leo60228** [comment]
Will be fixed in 1.3.
